"""
AI router — stubs for Phase 4. Returns placeholder responses in Phase 1.
"""

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/ai", tags=["ai"])


class PatientSummaryRequest(BaseModel):
    patient_id: str


class DashboardInsightsRequest(BaseModel):
    pass


class AssistantRequest(BaseModel):
    question: str


class AIResponse(BaseModel):
    text: str
    model_used: str
    disclaimer: str = "⚠ Decision support only — clinician judgement required. AI output does not constitute a diagnosis or treatment recommendation."


_STUB_NOTE = "AI Clinical Insights powered by IBM watsonx.ai will be enabled in Phase 4."


@router.post("/patient-summary", response_model=AIResponse)
def ai_patient_summary(payload: PatientSummaryRequest):
    return AIResponse(
        text=f"[Phase 4] AI summary for patient {payload.patient_id} will be generated by IBM watsonx.ai Granite. {_STUB_NOTE}",
        model_used="stub",
    )


@router.post("/dashboard-insights", response_model=AIResponse)
def ai_dashboard_insights():
    return AIResponse(
        text=f"[Phase 4] Dashboard-level AI insights will be generated by IBM watsonx.ai Granite. {_STUB_NOTE}",
        model_used="stub",
    )


@router.post("/assistant", response_model=AIResponse)
def ai_assistant(payload: AssistantRequest):
    return AIResponse(
        text=f"[Phase 4] Clinician AI Assistant powered by IBM watsonx.ai Granite. Your question: \"{payload.question}\". {_STUB_NOTE}",
        model_used="stub",
    )
